import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Noontree', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        primary: ['Noontree', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        noontree: ['Noontree', 'Figtree', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        tiny: ['10px', { lineHeight: '12px', letterSpacing: '0px' }],
        'label-2': ['14px', { lineHeight: '18px', letterSpacing: '-0.26px' }],
        'label-3': ['13px', { lineHeight: '16px', letterSpacing: '-0.26px' }],
        'label-3p': ['14px', { lineHeight: '18px', letterSpacing: '-0.14px' }],
        'label-4': ['14px', { lineHeight: '20px', letterSpacing: '-0.12px' }],
        'label-4p': ['12px', { lineHeight: '14px', letterSpacing: '-0.12px' }],
        'label-5': ['11px', { lineHeight: '12px', letterSpacing: '-0.12px' }],
        // ─── Field DS scale (heading / body / action) ────────────────────
        h40: ['40px', { lineHeight: '48px', letterSpacing: '-0.25px' }],
        h32: ['32px', { lineHeight: '40px', letterSpacing: '-0.25px' }],
        h28: ['28px', { lineHeight: '36px', letterSpacing: '-0.25px' }],
        h24: ['24px', { lineHeight: '32px', letterSpacing: '-0.25px' }],
        h20: ['20px', { lineHeight: '28px', letterSpacing: '-0.25px' }],
        h18: ['18px', { lineHeight: '24px', letterSpacing: '-0.15px' }],
        h16: ['16px', { lineHeight: '20px', letterSpacing: '-0.15px' }],
        b16: ['16px', { lineHeight: '20px', letterSpacing: '-0.15px' }],
        b14: ['14px', { lineHeight: '18px', letterSpacing: '-0.10px' }],
        b12: ['12px', { lineHeight: '16px', letterSpacing: '-0.10px' }],
        b11: ['11px', { lineHeight: '14px', letterSpacing: '-0.10px' }],
        a17: ['17px', { lineHeight: '24px', letterSpacing: '-0.25px' }],
        a16: ['16px', { lineHeight: '24px', letterSpacing: '0px' }],
        a14: ['14px', { lineHeight: '20px', letterSpacing: '0px' }],
        a12: ['12px', { lineHeight: '16px', letterSpacing: '0px' }],
      },
      colors: {
        neutral: { white: '#FFFFFF', black: '#000000' },
        'noon-yellow': '#FEEE00',
        'noon-red': '#F4364C',
        'blue-gray': {
          100: '#F9F9FB',
          200: '#F2F3F7',
          300: '#EAECF0',
          400: '#D4D6DD',
          500: '#A6ABB8',
          600: '#666D85',
          700: '#475067',
          800: '#2E3553',
          900: '#1D2539',
          1000: '#101628',
        },
        blue: {
          50: '#EFF7FF',
          100: '#E1EFFF',
          400: '#3D7CFF',
          500: '#0076FF',
          600: '#0076FF',
          700: '#0057FF',
          pin: '#035794',
        },
        red: {
          50: '#FEEBEB',
          100: '#FCD2D2',
          600: '#F43333',
          700: '#DE1C1C',
        },
        green: {
          50: '#F2FBF5',
          100: '#E5F6E6',
          600: '#108757',
          700: '#0E875E',
        },
        ink: {
          DEFAULT: 'rgba(2,6,12,0.92)',
          secondary: 'rgba(2,6,12,0.6)',
          tertiary: 'rgba(2,6,12,0.4)',
          inverse: '#FFFFFF',
        },
        'surface-primary': '#FFFFFF',

        'noon-black': '#404553',
        'noon-blue': '#3866DF',
        accent: {
          50:  '#eff7ff',
          100: '#e1efff',
          300: '#96c6ff',
          400: '#71b2ff',
          500: '#2a8dff',
          600: '#0076ff',
          700: '#0057ff',
        },
        bluegray: {
          50:   '#fcfcfd',
          100:  '#f9f9fb',
          200:  '#f2f3f7',
          300:  '#eaecf0',
          400:  '#d0d4dd',
          500:  '#989fb3',
          600:  '#666d85',
          700:  '#475067',
          800:  '#343d54',
          900:  '#1d2539',
          1000: '#101628',
        },
        emerald: {
          50:  '#e8fcfa',
          700: '#1f7a74',
          800: '#13645f',
          900: '#0a4f4a',
        },
        purple: {
          50:  '#f1eefc',
          100: '#e0d8fd',
          700: '#bf3deb',
        },
        orange: {
          50: '#fff7ed',
        },
        'persian-blue': '#4146ce',
        // ─── Field DS semantic colors (resolve via @tokens CSS vars) ─────
        text: {
          primary:           'var(--color-text-primary)',
          secondary:         'var(--color-text-secondary)',
          tertiary:          'var(--color-text-tertiary)',
          muted:             'var(--color-text-muted)',
          action:            'var(--color-text-action)',
          supermall:         'var(--color-text-supermall)',
          error:             'var(--color-text-error)',
          warning:           'var(--color-text-warning)',
          success:           'var(--color-text-success)',
          'yellow-light':    'var(--color-text-yellow-light)',
          'yellow-dark':     'var(--color-text-yellow-dark)',
          'on-surface-bold':   'var(--color-text-on-surface-bold)',
          'on-surface-subtle': 'var(--color-text-on-surface-subtle)',
        },
        surface: {
          primary:            'var(--color-surface-primary)',
          secondary:          'var(--color-surface-secondary)',
          tertiary:           'var(--color-surface-tertiary)',
          muted:              'var(--color-surface-muted)',
          'action-subtle':    'var(--color-surface-action-subtle)',
          'action-bold':      'var(--color-surface-action-bold)',
          'action-extrabold': 'var(--color-surface-action-extrabold)',
          'supermall-subtle': 'var(--color-surface-supermall-subtle)',
          'supermall-bold':   'var(--color-surface-supermall-bold)',
          'error-subtle':     'var(--color-surface-error-subtle)',
          'error-bold':       'var(--color-surface-error-bold)',
          'warning-subtle':   'var(--color-surface-warning-subtle)',
          'warning-bold':     'var(--color-surface-warning-bold)',
          'yellow-subtle':    'var(--color-surface-yellow-subtle)',
          'yellow-mild':      'var(--color-surface-yellow-mild)',
          'yellow-bold':      'var(--color-surface-yellow-bold)',
          'success-subtle':   'var(--color-surface-success-subtle)',
          'success-bold':     'var(--color-surface-success-bold)',
          'brand-primary':    'var(--color-surface-brand-primary)',
          'overlay-subtle':   'var(--color-surface-overlay-subtle)',
          'overlay-bold':     'var(--color-surface-overlay-bold)',
          'tertiary-inverted':  'var(--color-surface-tertiary-inverted)',
          'secondary-inverted': 'var(--color-surface-secondary-inverted)',
          'primary-inverted':   'var(--color-surface-primary-inverted)',
        },
        border: {
          primary:      'var(--color-border-primary)',
          subtle:       'var(--color-border-subtle)',
          medium:       'var(--color-border-medium)',
          bold:         'var(--color-border-bold)',
          extrabold:    'var(--color-border-extrabold)',
          action:       'var(--color-border-action)',
          'action-bold':'var(--color-border-action-bold)',
          supermall:    'var(--color-border-supermall)',
          error:        'var(--color-border-error)',
          warning:      'var(--color-border-warning)',
          yellow:       'var(--color-border-yellow)',
          success:      'var(--color-border-success)',
        },
        'alpha-dark': {
          4:  'var(--alpha-dark-4)',
          8:  'var(--alpha-dark-8)',
          16: 'var(--alpha-dark-16)',
          24: 'var(--alpha-dark-24)',
          50: 'var(--alpha-dark-50)',
          64: 'var(--alpha-dark-64)',
          80: 'var(--alpha-dark-80)',
        },
        'alpha-light': {
          4:  'var(--alpha-light-4)',
          8:  'var(--alpha-light-8)',
          16: 'var(--alpha-light-16)',
          24: 'var(--alpha-light-24)',
          50: 'var(--alpha-light-50)',
          64: 'var(--alpha-light-64)',
          80: 'var(--alpha-light-80)',
        },
      },
      borderRadius: {
        4: '4px',
        8: '8px',
        12: '12px',
        16: '16px',
        24: '24px',
        32: '32px',
      },
      boxShadow: {
        xs: '0 1px 3px rgba(34,34,34,0.06)',
        'inset-toggle': 'inset 0 0 4px 0 rgba(14,14,14,0.06)',
        sheet: '0 -8px 24px rgba(0,0,0,0.08)',
      },
      letterSpacing: {
        'label-2': '-0.26px',
        'label-5': '-0.12px',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        marquee: 'marquee 18s linear infinite',
        shimmer: 'shimmer 1.6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
} satisfies Config
